/**
 * @module @outpost/protocol
 *
 * Core wire protocol types, validators, and helpers shared between Mothership,
 * Beacon, and Outpost Daemon.
 *
 * This package defines the typed command vocabulary, relay message formats,
 * pairing payloads, signed envelopes, and release metadata that all peers
 * agree on. It contains no runtime dependencies beyond Node.js built-ins.
 */

/**
 * Current protocol version string used in all wire messages.
 *
 * @defaultValue "outpost.v1"
 */
export const PROTOCOL_VERSION = "outpost.v1";

/** Identifies which side of a relay connection a peer represents. */
export type PeerRole = "mothership" | "outpost";

/**
 * Lifecycle states an Outpost daemon can be in.
 *
 * @see `OutpostStatusReport`
 */
export type OutpostState =
  | "UNINITIALIZED"
  | "UNPAIRED"
  | "PAIRING"
  | "PAIRED_ONLINE"
  | "PAIRED_OFFLINE"
  | "DEPLOYING"
  | "ROLLING_BACK"
  | "ERROR";

/**
 * Typed commands that can be sent from Mothership to an Outpost.
 *
 * In Beacon strict mode the daemon accepts **only** these commands.
 * Every command is wrapped in a {@link SignedEnvelope} and verified
 * before execution.
 */
export type OutpostCommand =
  | { type: "PING" }
  | { type: "DEPLOY"; appId?: string; ref?: string; branch?: string; commit?: string }
  | { type: "ROLLBACK"; appId?: string; releaseId: string }
  | { type: "SET_ENV"; appId?: string; encryptedEnv: string }
  | { type: "DETECT_APP"; projectPath?: string }
  | { type: "RUN_HEALTH_CHECK"; appId?: string; url?: string }
  | {
      type: "APPLY_RECIPE";
      appId?: string;
      recipeId: string;
      approvedParameters: Record<string, unknown>;
    }
  | { type: "DOCTOR" }
  | { type: "GET_STATE" };

/**
 * Metadata persisted for each published release.
 *
 * @see `publishRelease` in `@outpost/shared/releases`
 */
export type ReleaseMetadata = {
  /** Unique release identifier, typically `<timestamp>-<short-commit>`. */
  releaseId: string;
  /** ISO-8601 timestamp when the release was created. */
  createdAt: string;
  /** Git branch that was checked out during the build, if any. */
  branch?: string;
  /** Git commit SHA that the release was built from. */
  commit: string;
  /** Whether the build and publish succeeded. */
  status: "success" | "failed";
  /** Build command that produced the release. */
  buildCommand: string;
  /** Directory that was copied into the release. */
  outputDir: string;
  /** Build duration in milliseconds. */
  durationMs: number;
};

/**
 * Full status report returned by an Outpost in response to
 * {@link OutpostCommand} `GET_STATE`.
 */
export type OutpostStatusReport = {
  /** Current lifecycle state. */
  state: OutpostState;
  /** Human-readable project name from config. */
  projectName: string;
  /** Optional host label set during setup. */
  hostLabel?: string;
  /** Currently active release ID, if any. */
  currentReleaseId?: string;
  /** Branch of the currently active release. */
  currentBranch?: string;
  /** Commit of the currently active release. */
  currentCommit?: string;
  /** All known releases sorted by ID. */
  releases: ReleaseMetadata[];
  /** Last recorded error message, if any. */
  lastError?: string;
};

/**
 * Single line emitted during a deployment build.
 *
 * @see `BuildLogEvent`
 */
export type BuildLogEvent = {
  /** Deployment / build session identifier. */
  deploymentId: string;
  /** Which stream the line came from. */
  stream: "stdout" | "stderr" | "system";
  /** Raw log line text. */
  line: string;
  /** ISO-8601 timestamp. */
  createdAt: string;
};

/**
 * Result returned by an Outpost after executing a typed command.
 */
export type CommandResult = {
  /** The command type that was executed. */
  commandType: OutpostCommand["type"];
  /** Whether the command succeeded. */
  ok: boolean;
  /** Human-readable message or error text. */
  message?: string;
  /** Release ID produced by DEPLOY / APPLY_RECIPE, if any. */
  releaseId?: string;
  /** Exit code when the command wrapped a shell process. */
  exitCode?: number;
  /** Arbitrary structured result data. */
  data?: unknown;
};

/**
 * Pairing token payload generated by Mothership and consumed by
 * `outpost-daemon setup --pair <token>`.
 *
 * @see `createPairingCommand` in `@outpost/mothership/state`
 */
export type PairingPayload = {
  /** Must equal {@link PROTOCOL_VERSION}. */
  protocolVersion: typeof PROTOCOL_VERSION;
  /** WebSocket URL of the Beacon relay to connect to. */
  beaconUrl: string;
  /** Mothership Ed25519 public key in PEM format. */
  mothershipPublicKey: string;
  /** Mothership peer ID derived from its public key. */
  mothershipPeerId: string;
  /** Unique nonce used during the pairing handshake. */
  pairingNonce: string;
  /** ISO-8601 timestamp when the payload was created. */
  createdAt: string;
  /** ISO-8601 timestamp after which the payload is no longer valid. */
  expiresAt: string;
  /** Optional human-readable display name for the target app. */
  displayName?: string;
  /** Optional build overrides forwarded to the Outpost config. */
  buildHints?: {
    installCommand?: string;
    buildCommand?: string;
    outputDir?: string;
    projectName?: string;
    retainReleases?: number;
  };
};

/**
 * Initial hello message sent by a newly-paired Outpost to Mothership
 * through the Beacon relay.
 */
export type PairingHello = {
  type: "PAIRING_HELLO";
  /** Must equal {@link PROTOCOL_VERSION}. */
  protocolVersion: typeof PROTOCOL_VERSION;
  /** Same nonce from the consumed {@link PairingPayload}. */
  pairingNonce: string;
  /** Outpost Ed25519 public key in PEM format. */
  outpostPublicKey: string;
  /** Human-readable project name. */
  projectName: string;
  /** Optional host label. */
  hostLabel?: string;
};

/**
 * Cryptographically signed envelope that wraps every command and status
 * message sent between Mothership and Outpost.
 *
 * @remarks
 * The payload itself is the only mutable field; all envelope metadata is
 * included in the signed canonical JSON so that tampering is detectable.
 */
export type SignedEnvelope<TPayload = unknown> = {
  protocolVersion: typeof PROTOCOL_VERSION;
  /** Unique message ID for idempotency / replay detection. */
  messageId: string;
  /** Peer ID of the sender. */
  senderId: string;
  /** Peer ID of the intended recipient. */
  recipientId: string;
  /** ISO-8601 timestamp when the envelope was issued. */
  issuedAt: string;
  /** ISO-8601 timestamp after which the envelope must be rejected. */
  expiresAt: string;
  /** Random nonce to prevent replay attacks. */
  nonce: string;
  /** Typed command or status payload. */
  payload: TPayload;
  /** Ed25519 detached signature (base64url). */
  signature: string;
};

/** Structure for an encrypted payload (not yet used by the core protocol). */
export type EncryptedPayload = {
  keyId: string;
  ephemeralPublicKey: string;
  iv: string;
  authTag: string;
  ciphertext: string;
};

/** Client-to-relay registration message. */
export type RelayRegisterMessage = {
  type: "REGISTER";
  role: PeerRole;
  peerId: string;
  pairingNonce?: string;
};

/** Client-to-relay forward message. */
export type RelayForwardMessage = {
  type: "FORWARD";
  from: string;
  to: string;
  body: unknown;
};

/** Messages the relay server sends back to connected clients. */
export type RelayServerMessage =
  | { type: "REGISTERED"; peerId: string }
  | { type: "PEER_ONLINE"; peerId: string }
  | { type: "PEER_OFFLINE"; peerId: string }
  | { type: "FORWARD"; from: string; body: unknown }
  | { type: "ERROR"; message: string };

/** Union of all messages a relay client may send. */
export type RelayClientMessage = RelayRegisterMessage | RelayForwardMessage;

/**
 * Type guard: checks whether a value is a plain object (not null, not array).
 *
 * @param value - Value to inspect.
 * @returns `true` when value is a non-null, non-array object.
 */
export function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Asserts that a value is a non-empty string.
 *
 * @param value - Value to validate.
 * @param field - Human-readable field name for error messages.
 * @returns The validated string.
 * @throws Error if the value is not a non-empty string.
 */
export function asString(value: unknown, field: string): string {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`Expected ${field} to be a non-empty string`);
  }
  return value;
}

/**
 * Asserts that a value is either `undefined` or a string.
 *
 * @param value - Value to validate.
 * @param field - Human-readable field name for error messages.
 * @returns The validated string, or `undefined`.
 * @throws Error if the value is defined but not a string.
 */
export function asOptionalString(value: unknown, field: string): string | undefined {
  if (value === undefined) {
    return undefined;
  }
  if (typeof value !== "string") {
    throw new Error(`Expected ${field} to be a string when provided`);
  }
  return value;
}

/**
 * Asserts that a value is either `undefined` or a plain object.
 *
 * @param value - Value to validate.
 * @param field - Human-readable field name for error messages.
 * @returns The validated record, or `undefined`.
 * @throws Error if the value is defined but not a plain object.
 */
export function asOptionalRecord(
  value: unknown,
  field: string
): Record<string, unknown> | undefined {
  if (value === undefined) {
    return undefined;
  }
  if (!isRecord(value)) {
    throw new Error(`Expected ${field} to be an object when provided`);
  }
  return value;
}

/**
 * Validates and parses an untrusted value into a {@link PairingPayload}.
 *
 * @param value - Untrusted input, typically parsed JSON.
 * @returns A fully-typed pairing payload.
 * @throws Error when the payload is malformed or uses an unsupported protocol version.
 */
export function parsePairingPayload(value: unknown): PairingPayload {
  if (!isRecord(value)) {
    throw new Error("Pairing payload must be an object");
  }
  const protocolVersion = asString(value.protocolVersion, "protocolVersion");
  if (protocolVersion !== PROTOCOL_VERSION) {
    throw new Error(`Unsupported protocol version: ${protocolVersion}`);
  }
  return {
    protocolVersion,
    beaconUrl: asString(value.beaconUrl, "beaconUrl"),
    mothershipPublicKey: asString(value.mothershipPublicKey, "mothershipPublicKey"),
    mothershipPeerId: asString(value.mothershipPeerId, "mothershipPeerId"),
    pairingNonce: asString(value.pairingNonce, "pairingNonce"),
    createdAt: asString(value.createdAt, "createdAt"),
    expiresAt: asString(value.expiresAt, "expiresAt"),
    displayName: asOptionalString(value.displayName, "displayName"),
    buildHints: parseBuildHints(value.buildHints)
  };
}

function parseBuildHints(value: unknown): PairingPayload["buildHints"] {
  if (value === undefined) {
    return undefined;
  }
  if (!isRecord(value)) {
    throw new Error("Expected buildHints to be an object when provided");
  }
  const retainReleases = value.retainReleases;
  if (retainReleases !== undefined && typeof retainReleases !== "number") {
    throw new Error("Expected buildHints.retainReleases to be a number when provided");
  }
  return {
    installCommand: asOptionalString(value.installCommand, "buildHints.installCommand"),
    buildCommand: asOptionalString(value.buildCommand, "buildHints.buildCommand"),
    outputDir: asOptionalString(value.outputDir, "buildHints.outputDir"),
    projectName: asOptionalString(value.projectName, "buildHints.projectName"),
    retainReleases
  };
}

/**
 * Validates and parses an untrusted value into an {@link OutpostCommand}.
 *
 * @param value - Untrusted input, typically parsed JSON.
 * @returns A fully-typed command.
 * @throws Error when the command is malformed or the type is unsupported.
 */
export function parseOutpostCommand(value: unknown): OutpostCommand {
  if (!isRecord(value)) {
    throw new Error("Command must be an object");
  }
  const type = asString(value.type, "type");
  switch (type) {
    case "PING":
    case "DOCTOR":
    case "GET_STATE":
      return { type };
    case "DEPLOY":
      return {
        type,
        appId: asOptionalString(value.appId, "appId"),
        ref: asOptionalString(value.ref, "ref"),
        branch: asOptionalString(value.branch, "branch"),
        commit: asOptionalString(value.commit, "commit")
      };
    case "ROLLBACK":
      return {
        type,
        appId: asOptionalString(value.appId, "appId"),
        releaseId: asString(value.releaseId, "releaseId")
      };
    case "SET_ENV":
      return {
        type,
        appId: asOptionalString(value.appId, "appId"),
        encryptedEnv: asString(value.encryptedEnv, "encryptedEnv")
      };
    case "DETECT_APP":
      return { type, projectPath: asOptionalString(value.projectPath, "projectPath") };
    case "RUN_HEALTH_CHECK":
      return {
        type,
        appId: asOptionalString(value.appId, "appId"),
        url: asOptionalString(value.url, "url")
      };
    case "APPLY_RECIPE":
      return {
        type,
        appId: asOptionalString(value.appId, "appId"),
        recipeId: asString(value.recipeId, "recipeId"),
        approvedParameters: asOptionalRecord(value.approvedParameters, "approvedParameters") ?? {}
      };
    default:
      throw new Error(`Unsupported command type: ${type}`);
  }
}

/**
 * Validates and parses an untrusted value into a {@link RelayClientMessage}.
 *
 * @param value - Untrusted input, typically parsed JSON.
 * @returns A fully-typed relay client message.
 * @throws Error when the message is malformed.
 */
export function parseRelayClientMessage(value: unknown): RelayClientMessage {
  if (!isRecord(value)) {
    throw new Error("Relay message must be an object");
  }
  const type = asString(value.type, "type");
  if (type === "REGISTER") {
    const role = asString(value.role, "role");
    if (role !== "mothership" && role !== "outpost") {
      throw new Error(`Invalid role: ${role}`);
    }
    return {
      type,
      role,
      peerId: asString(value.peerId, "peerId"),
      pairingNonce: asOptionalString(value.pairingNonce, "pairingNonce")
    };
  }
  if (type === "FORWARD") {
    return {
      type,
      from: asString(value.from, "from"),
      to: asString(value.to, "to"),
      body: value.body
    };
  }
  throw new Error(`Unsupported relay message type: ${type}`);
}

/**
 * Serialises a value to JSON and encodes it as a base64 string.
 *
 * @param value - Any JSON-serialisable value.
 * @returns Base64-encoded JSON.
 */
export function encodeJsonBase64(value: unknown): string {
  return Buffer.from(JSON.stringify(value), "utf8").toString("base64");
}

/**
 * Decodes a base64 string and parses it as JSON.
 *
 * @param value - Base64-encoded JSON.
 * @returns The parsed value.
 * @throws SyntaxError when the payload is not valid JSON.
 */
export function decodeJsonBase64(value: string): unknown {
  return JSON.parse(Buffer.from(value, "base64").toString("utf8"));
}
